import type { Metadata } from "next";
import { Cinzel, Open_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import ReactLenis from "lenis/react";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

const opensans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${opensans.className} ${playfair.variable} ${cinzel.variable} antialiased lg:overflow-hidden`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
